### ISSUE TITLE
Rendering broken on OS X

### ISSUE THREAD

**Issue by AndrewLavin** [anoek/ex-sdl-cairo-freetype-harfbuzz#1]
Thank you for providing this nice harfbuzz sample code.

It seems not to work correctly on OS X 10.7.5. The glyph advances appear to be much to small, so the characters are rendered on top of each other. I have a screenshot.

Compiled with libsdl and cairo from Macports.

**Comment by saeidtofig** [comment]
Thank you
I Can't use this sample code. i need to download harfbaz and cairo and sdl for use this sample? where cand find this projects. i want tu use this sample in windows8 os and turbo c++. how i can use?
