### ISSUE TITLE
Memory usage

### ISSUE THREAD

**Issue by foodornt** [anoek/ex-sdl-cairo-freetype-harfbuzz#13]
This is more of a question really, not an issue

what's making this sample code use ~140MiB of memory?

**Comment by anoek** [comment]
I wouldn't know without doing a pretty deep dive, but that doesn't seem that crazy given the number of things that has to come together to put some pixels on the screen, especially when you consider these libraries are probably doing a fair amount of internal caching of graphics and all of that.
