### ISSUE TITLE
Please clarify the license

### ISSUE THREAD

**Issue by emg** [anoek/ex-sdl-cairo-freetype-harfbuzz#7]
Hello,

thank you for providing this excellent example.  It is very helpful.

Please clarify the license somewhere, e.g., README.md or COPYING.txt.

Thanks very much.

Best wishes,

Ulrik Sandborg-Petersen

**Comment by anoek** [comment]
There we go, permissive zero clause BSD license.

**Comment by emg** [comment]
Many, many thanks. Your generosity and time are highly appreciated.

Have a good day.

Best wishes,

Ulrik Sandborg-Petersen
